import {
  SiReact,
  SiNextdotjs,
  SiTypescript,
  SiJavascript,
  SiVite,
  SiHtml5,
  SiCss,
  SiSass,
  SiRedux,
  SiMui,
  SiTailwindcss,
  SiJest,
  SiVitest,
  SiCypress,
  SiNodedotjs,
  SiExpress,
  SiMongodb,
  SiPostgresql,
  SiPrisma,
  SiGithubcopilot,
  SiPostman,
} from 'react-icons/si'
import type { IconType } from 'react-icons'

export const ICON_MAP: Record<string, IconType> = {
  React: SiReact,
  'React Native': SiReact,
  'Next.js': SiNextdotjs,
  TypeScript: SiTypescript,
  JavaScript: SiJavascript,
  Vite: SiVite,
  HTML: SiHtml5,
  CSS: SiCss,
  Sass: SiSass,
  Redux: SiRedux,
  'Material UI': SiMui,
  'Tailwind CSS': SiTailwindcss,
  Jest: SiJest,
  Vitest: SiVitest,
  Cypress: SiCypress,
  Postman: SiPostman,
  'Node.js': SiNodedotjs,
  Express: SiExpress,
  MongoDB: SiMongodb,
  PostgreSQL: SiPostgresql,
  Prisma: SiPrisma,
  'GitHub Copilot': SiGithubcopilot,
}
